import {ROOMS,WEAPONS,UPGRADES} from './content.js?v=10';
import {availableEvolutions} from './combinations.js?v=10';
export function recapData(g){
 const counts=new Map();for(const id of g.loadout)counts.set(id,(counts.get(id)||0)+1);
 const combos=[['parcels','回收包开启'],['windowHits','喘气窗口命中'],['electricHits','电弧命中'],['chargedPops','带电爆泡'],['relays','拖把接力'],['discRelays','刷盘接力'],['foamShots','泡沫裹弹'],['bucketRecovered','泥桶回收'],['returns','弹球回收']].filter(([key])=>(g.stats[key]||0)>0).map(([key,name])=>({name,count:Math.round(g.stats[key])}));
 return {combos,build:[...counts].map(([id,n])=>({name:UPGRADES.find(u=>u.id===id)?.name||id,n})),evolutions:availableEvolutions(g),cleanWins:g.roomResults.filter(r=>r.reason==='clean').length,combatWins:g.roomResults.filter(r=>r.reason==='combat').length};
}
export function renderRunRecap(g){
 const d=recapData(g),won=g.state==='won',secs=Math.round(g.time),weapon=WEAPONS.find(w=>w.id===g.weapon);
 const places=[['garden','花园','courtyard'],['greenhouse','温室','greenhouse-v1'],['workshop','工坊','workshop-v1']];
 return `<div class="modal recap-modal"><span class="modal-eyebrow">CLEANING CLUB · 今日清洁手帐</span><h2>${won?'把十二处小天地，还给了晴天。':'先歇一会，这些地方已经焕然一新。'}</h2><p>${g.roomResults.length} / ${ROOMS.length} 处收拾妥当 · ${d.combatWins} 次清空捣蛋鬼 · ${d.cleanWins} 次清洁达标</p><div class="recap-actions"><button class="primary" id="again">${won?'保留开局装备，再来一局':'再试一次'} ↗</button><button class="secondary" id="new-kit">换套开局装备</button><button class="secondary" id="export">保存这一局的记录 ↓</button></div><div class="recap-places">${places.map(([theme,name,img])=>{const rooms=ROOMS.map((r,i)=>({...r,room:i+1,theme:i<4?'garden':r.theme})).filter(r=>r.theme===theme),done=rooms.filter(r=>g.roomResults.some(v=>v.room===r.room)).length;return `<figure class="${done?'':'unvisited'}"><img src="assets/illustrated/${img}.webp" alt="${name}清洁后的场景"/><figcaption><strong>${name}</strong><span>${done} / ${rooms.length} 处完成</span></figcaption></figure>`;}).join('')}</div><div class="recap-numbers"><span><b>${g.stats.kills}</b> 只捣蛋鬼</span><span><b>${g.stats.shots}</b> 发垃圾弹</span><span><b>${Math.floor(secs/60)}:${String(secs%60).padStart(2,'0')}</b> 清洁用时</span></div><div class="recap-build"><strong>${weapon.name} · 这一局的装备</strong><div>${d.build.map(b=>`<span>${b.name}${b.n>1?' ×'+b.n:''}</span>`).join('')||'<span>基础清洁器</span>'}</div>${d.evolutions.length?`<p class="recap-evolved">✦ 已成型：${d.evolutions.map(e=>e.name).join(' · ')}</p>`:''}</div><details class="recap-details"><summary>翻看清洁路线与实际连携</summary><div class="recap-route">${g.roomResults.map(r=>`<span title="${ROOMS[r.room-1].name} · ${r.flavor||''}">${String(r.room).padStart(2,'0')} ${r.reason==='clean'?'清洁':'清怪'} · ${Math.round(r.seconds)}秒</span>`).join('')||'这一处还没收拾完。'}</div><p>${d.combos.length?d.combos.map(v=>`${v.name} ${v.count} 次`).join(' · '):'本局尚未记录到连携触发。'}</p></details><small class="recap-note">重开保留清洁器与开局伙伴，局内升级重新获取。</small></div>`;
}
